### ISSUE TITLE
sbt  test fail 

### ISSUE THREAD

**Issue by pxs7** [ucb-bar/berkeley-hardfloat#62]
at scala.sys.process.ProcessImpl$PipeThread.runloop(ProcessImpl.scala:170)
        at scala.sys.process.ProcessImpl$PipeSource.run(ProcessImpl.scala:188)
I/O error Pipe closed for process: [testfloat_gen, -rnear_maxMag, -tininessbefore, f16_add]
java.io.IOException: Pipe closed
        at java.base/java.io.PipedInputStream.checkStateForReceive(PipedInputStream.java:260)
        at java.base/java.io.PipedInputStream.awaitSpace(PipedInputStream.java:268)
        at java.base/java.io.PipedInputStream.receive(PipedInputStream.java:231)
        at java.base/java.io.PipedOutputStream.write(PipedOutputStream.java:149)
        at scala.sys.process.BasicIO$.loop$1(BasicIO.scala:240)
        at scala.sys.process.BasicIO$.transferFullyImpl(BasicIO.scala:246)
        at scala.sys.process.BasicIO$.transferFully(BasicIO.scala:227)
        at scala.sys.process.ProcessImpl$PipeThread.runloop(ProcessImpl.scala:170)
        at scala.sys.process.ProcessImpl$PipeSource.run(ProcessImpl.scala:188)
I/O error Pipe closed for process: [testfloat_gen, -rminMag, -tininessbefore, -level2, f16_to_f32]
java.io.IOException: Pipe closed
        at java.base/java.io.PipedInputStream.checkStateForReceive(PipedInputStream.java:260)
        at java.base/java.io.PipedInputStream.awaitSpace(PipedInputStream.java:268)
        at java.base/java.io.PipedInputStream.receive(PipedInputStream.java:231)

**Comment by michael-etzkorn** [comment]
Potential issues are easier to debug if you explain the steps you took. Just running `sbt test` is unsupported. Did you manually uild the prerequisits by first running `$(MAKE) -C berkeley-testfloat-3/build/Linux-x86_64-GCC SPECIALIZE_TYPE=RISCV`?


The recommended test flow is using `make`.
